name: Pytest Testing
on:
  pull_request:
    types: [opened,reopened,synchronize]
  push:
    branches:    
      - 'main'
      - 'releases/**'
jobs:
  test:
    name: pytest
    runs-on: 'ubuntu-latest'
    env:
      OS: 'ubuntu-latest'
      PYTHON: '3.9'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Environment
        run: |
          gcc --version
          sudo apt update
          sudo apt remove gcc
          sudo apt install gcc-12
          gcc --version
          python -m pip install --upgrade pip
          pip install '.[jwst,hst,pymc3,test]'
          conda install mkl-service
          mkdir $HOME/crds_cache
          echo "CRDS_PATH=$HOME/crds_cache" >> $GITHUB_ENV
          echo "CRDS_SERVER_URL=https://jwst-crds.stsci.edu" >> $GITHUB_ENV
      - name: Log the current Eureka version
        run: pip show eureka
      - name: Run tests, generate coverage report
        run: pytest tests --cov=./src/eureka --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,PYTHON
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
